name: nwaslouk
description: Nwaslouk â€“ Louage travel companion in Tunisia. Clean architecture, Riverpod, Dio, get_it, dotenv, logger.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State management
  flutter_riverpod: ^2.5.1

  # Dependency injection
  get_it: ^7.7.0

  # Networking
  dio: ^5.5.0+1

  # Env config
  flutter_dotenv: ^5.1.0

  # Logging
  logger: ^2.4.0

  # Functional types
  dartz: ^0.10.1

  # Local storage (optional)
  shared_preferences: ^2.3.2

  # Routing (optional basic Navigator used; can switch to go_router later)

  # Lints
  flutter_lints: ^4.0.0

  # JSON serialization (optional for future)
  json_annotation: ^4.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  build_runner: ^2.4.13
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - env/
    - env/